language:       python
python:
  - "3.6"
# command to install dependencies
before_install:
  - export PYTHONPATH="$PYTHONPATH:ctlai95/python-tetris"
install:
  - pip3 install pyglet
  - pip3 install pytest
# command to run tests
script:         pytest -v
